### ISSUE TITLE
Import markdown files with frontmatter yaml?

### ISSUE THREAD

**Issue by justyns** [Nriver/trilium-py#24]
Thanks for creating this library!  I've only just started testing out Trilium, but I'm liking it so far.   One of the things I'd like to do is import all of my old notes from Joplin and Obsidian.

I used a script similar to the one in the README but noticed yaml frontmatter doesn't get preserved.  For example, a joplin exported note like this:

``` yaml
---
title: 2021-03-05 - hvac furnace tune up
updated: 2021-03-05 15:27:20Z
created: 2021-03-05 13:43:07Z
latitude: xx.xx
longitude: -yy.yy
altitude: 101
---

note contents here
```

Gets turned into this (when viewing the source of the trilium note):

``` html
<hr />

<p>title: 2021-03-05 - hvac furnace tune up
updated: 2021-03-05 15:27:20Z
created: 2021-03-05 13:43:07Z
latitude: xx.xx
longitude: -yy.yy</p>

<h2>altitude: 101</h2>

<p>note contents here</p>
```

Is it possible (and does it make sense) to convert that yaml frontmatter and turn it into attributes on the note?  For my example, I think it'd get turned into something like `#latitude=xx.xx #longitude=-yy.yy #altitude=101 `.

I've used https://pypi.org/project/python-frontmatter/ in the past and it worked okay.   I haven't looked much at the code here or the trilium api, but I might try to take a look this weekend if I continue w/ trilium.
